Created rest endpoint on obs to service the registration of a bank account
ADORSYS-GIS/webank-OnlineBanking pull request #39
Opened 2024-10-23 13:22 UTC by Arielpetit

Created rest endpoint on obs to service the registration of a bank account
[DESCRIPTION](https://github.com/orgs/ADORSYS-GIS/projects/14/views/4?sliceBy%5Bvalue%5D=Sprint1&pane=issue&itemId=83580595&issue=ADORSYS-GIS%7Cwebank-OnlineBanking%7C24)

2024-10-24 07:55 UTC, francis-pouatcha requested changes

2024-10-24 07:55 UTC, francis-pouatcha commented on obs/obs-rest-server/pom.xml
> +            <version>1.18.24</version> <!-- Check for the latest version -->
Please add lombok version to the parent property

2024-10-24 07:55 UTC, francis-pouatcha commented on online-banking-app/pom.xml
> +			<version>2.1.0</version>
Please send version number to top most parent pom. And declare dependency in the dependency management of that pom.

2024-10-24 07:55 UTC, francis-pouatcha commented on online-banking-app/src/test/java/com/adorsys/webank/OnlineBankingApplicationTests.java
> +//}
Why not just delete the file?

2024-10-25 07:48 UTC, NkwaTambe approved these changes

2024-10-25 08:00 UTC, Koufan-De-King requested changes

2024-10-25 08:00 UTC, Koufan-De-King commented on tash apply
This file should be removed.

2024-10-25 08:00 UTC, Koufan-De-King commented on obs/obs-rest-api/pom.xml
> +        <dependency>
The version for this dependency should be derived from the parent pom.

2024-10-25 08:04 UTC, Elwizzy12 approved these changes

2024-10-25 08:08 UTC, Koufan-De-King submitted a review, later dismissed
Great!

2024-10-25 08:09 UTC, NkwaTambe approved these changes

2024-10-25 08:10 UTC, yvanhenang submitted a review, later dismissed

2024-10-25 10:19 UTC, francis-pouatcha commented on obs/obs-service-impl/pom.xml
> +        </dependency>
remove this

2024-10-25 10:20 UTC, francis-pouatcha requested changes
Please see my comments

2024-10-25 11:55 UTC, nancymuyeh approved these changes

2024-10-25 11:56 UTC, Koufan-De-King approved these changes

2024-10-25 11:59 UTC, Elwizzy12 approved these changes

2024-10-28 06:54 UTC, merged

2024-10-28 06:59 UTC, francis-pouatcha reviewed
Good for me