Create CI/CD for OBS
ADORSYS-GIS/webank-OnlineBanking pull request #61
Opened 2024-11-07 06:13 UTC by yvanhenang

2024-11-07 07:09 UTC, nancymuyeh requested changes

2024-11-07 07:09 UTC, nancymuyeh commented on .github/workflows/ci.cd.yml
> +      - name: Run PMD Check
You should comment this for now since we haven't set up pmd and  for now

2024-11-07 07:09 UTC, nancymuyeh commented on .github/workflows/ci.cd.yml
> +      - name: SonarQube Scan
Comment this as well for now

2024-11-08 08:27 UTC, nancymuyeh approved these changes

2024-11-11 15:04 UTC, Koufan-De-King approved these changes

2024-11-11 15:04 UTC, merged